SEED: 42 # random seed for reproduce results
DEVICE_IDS: '0'
USE_DDP: False
LOG_DIR: ""
RELOAD_PTH: ~


dataset:
    model_exp: '../model_exp'
    task_name: 'biome'
    train_dir: '/media/lorenzo/26DA3A93DA3A5F6D/data/datasets/SemanticSegmentation/Biome_cut'
    train_val_split: Ture
    train_val_split_ratio: 0.1

aug:
    is_aug: True
    SCALE: 1.125
    Mean: [0.5, 0.5, 0.5, 0.5]
    Std: [0.5, 0.5, 0.5, 0.5]
    HW: [512, 512]
    HFLIP: True
    VFLIP: False
    BLUR: True
    Brightness: 25
    ROTATE: 10
    CROP: True

model:
    model_name: 'unet'
    pretrained: True
    pretrained_model_url: "/home/lorenzo/PycharmProjects/SemanticSegmentation/Seg_model/model_exp/biome/unet/2022-01-31_11-39-01/model_best_loss.pth"
    n_channels: 4
    num_classes: 3
    bn: 'bn'
    loss: 'ce'

ddp:
    WORLD_SIZE: 1
    RANK: 0
    LOCAL_RANK: 0
    DIST_BACKEND: 'nccl' # 'nccl', 'gloo'
    DIST_URL: 'tcp://127.0.0.1:23456'  # "env://"  # 'tcp://127.0.0.1:23456'
    NUM_WORKERS: 8
    NPROCS: 4

train:
    optim: 'sgd'
    base_lr: 0.0001
    use_balanced_weights: False
    # base_lr: 0.03
    total_epochs: 120
    lr_scheduler: constant  # wucos / multistep / constant
    warmup_cosdecay: 10
    multistep_milestone: [10, 30, 80]
    batch_size: 24
    load_model: False
    model_file: ""
    print_freq: 100
    checkpoint_epochs: [50,100,]

test:
    # model_dir: '2019-0701-1906-53-100-stepDecay-0629c/'
    # model_dir: '2019-0626-1458-16-100-stepDecay-0619c/'
    test_dir: "/mnt/shy/sjh/Seg_data/iccv09Data/images"
    test_save_dir: "/mnt/shy/sjh/Seg_data/iccv09Data/masks_UNet"
    color_save_dir: "/mnt/shy/sjh/Seg_data/iccv09Data/masks_color_UNet"
    model_path: '/mnt/shy/sjh/seg_model/model_exp/unet/stanford/2021-11-11_18-20-22/model_final_150.pth'
    gpu: '5'
    batch_size: 16
