SEED: 42 # random seed for reproduce results
DEVICE_IDS: '0'
USE_DDP: False
LOG_DIR: ""
RELOAD_PTH: ~


dataset:
    model_exp: 'C:\PycharmProjects\SemanticSegmentation\Seg_model\model_exp'
    task_name: 'sparcs'
    train_dir: 'C:\Datasets\seg_data\mySPARCS'
    train_val_split: Ture
    train_val_split_ratio: 0.1

aug:
    is_aug: True
    Mean: [0.5, 0.5, 0.5] #　[0.247, 0.289, 0.213]
    Std: [0.5, 0.5, 0.5] # [0.095, 0.107, 0.110]
    HW: [384, 384]
    HFLIP: True
    VFLIP: False
    BLUR: True
    Brightness: 1.125
    CROP: True

model:
    model_name: 'unet'
    pretrained: False
    pretrained_model_url: ""
    num_classes: 3
    bn: 'bn'
    loss: 'ce'

ddp:
    WORLD_SIZE: 1
    RANK: 0
    LOCAL_RANK: 0
    DIST_BACKEND: 'nccl' # 'nccl', 'gloo'
    DIST_URL: 'tcp://127.0.0.1:23456'  # "env://"  # 'tcp://127.0.0.1:23456'
    NUM_WORKERS: 8
    NPROCS: 4

train:
    optim: 'sgd'
    base_lr: 0.01
    use_balanced_weights: False
    # base_lr: 0.03
    total_epochs: 120
    warmup_cosdecay: 10
    batch_size: 16
    load_model: False
    model_file: ""
    print_freq: 10
    checkpoint_epochs: [50,100,]

test:
    # model_dir: '2019-0701-1906-53-100-stepDecay-0629c/'
    # model_dir: '2019-0626-1458-16-100-stepDecay-0619c/'
    test_dir: "/mnt2/sjh/seg_data/mySPARCS/images/test"
    test_save_dir: "/mnt2/sjh/seg_data/mySPARCS/masks_UNet"
    color_save_dir: "/mnt2/sjh/seg_data/mySPARCS/masks_color_UNet"
    model_path: '/mnt/shy/sjh/seg_model/model_exp/sparcs/unet/2021-12-21_15-12-54/model_best_loss.pth'
    gpu: '5'
    batch_size: 16
