SEED: 666 # random seed for reproduce results
DEVICE_IDS: '1,2,3,4'
USE_DDP: True
LOG_DIR: ""
RELOAD_PTH: ~

ONE_HOT: False

dataset:
    model_exp: '../model_exp'
    task_name: 'sparcs'
    train_dir: '/mnt2/sjh/seg_data/mySPARCS'
    train_val_split: Ture
    train_val_split_ratio: 0.1

aug:
    is_aug: True
    Mean: [0.247, 0.289, 0.213]
    Std: [0.095, 0.107, 0.110]
    HW: [512, 512]
    HFLIP: True
    VFLIP: False
    BLUR: True
    Brightness: 1.25
    CROP: True

model:
    model_name: 'haoSegNet'
    pretrained: False
    channel_list: [32, 64, 128, 256, 256, 256]
    res_block_list: [2, 2, 2, 2, 2]
    pretrained_model_url: ""
    num_classes: 3
    bn: 'syncbn'
    loss: 'ce'

ddp:
    WORLD_SIZE: 1
    RANK: 0
    LOCAL_RANK: 0
    DIST_BACKEND: 'nccl' # 'nccl', 'gloo'
    DIST_URL: 'tcp://127.0.0.1:23456'  # "env://"  # 'tcp://127.0.0.1:23456'
    NUM_WORKERS: 8
    NPROCS: 4

train:
    optim: 'sgd'
    base_lr: 0.01
    use_balanced_weights: False
    total_epochs: 120
    warmup_cosdecay: 10
    batch_size: 16
    load_model: False
    model_file: ""
    print_freq: 10
    checkpoint_epochs: [50,100,]

test:
    test_dir: "/mnt2/sjh/seg_data/mySPARCS/images/test"
    test_save_dir: "/mnt2/sjh/seg_data/mySPARCS/masks_haoSegNet"
    color_save_dir: "/mnt2/sjh/seg_data/mySPARCS/masks_color_haoSegNet"
    model_path: '/mnt/shy/sjh/seg_model/model_exp/sparcs/unet/2021-12-20_14-28-38/model_best_loss.pth'
    gpu: '5'
    batch_size: 16
